apiVersion: V1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    version: V1
spec:
  containers:
    - name: my-nginx
      image: nginx
      resources: # Practicing to write the resource limits
        limits:
          memory: 50M
          cpu: 500M
